name = "killergg/feces"
version = "1.3.0"
description = "Fast Entity Component Export System: Generalized Replication for jecs."
authors = ["NeonD00m", "as8d"]
repository = "https://github.com/neond00m/feces"
license = "MIT"

includes = [
  "pesde.toml",
  "../README.md",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "auto.luau"
build_files = ["auto.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
core = { workspace = "killergg/feces_core", version = "^" }
world = { name = "killergg/jecs_world", version = "^0.1.3" }
refs = { name = "killergg/jecs_refs", version = "^0.1.0" }